apiVersion: v1
data:
  DB_DB: weby_desenv
  DB_HOST: 200.137.217.175
  DB_PORT: "5432"
  DB_USER: weby_desenv
  RAILS_ENV: production
  STORAGE_BUCKET: webyteste
  STORAGE_HOST: files.cercomp.ufg.br
kind: ConfigMap
metadata:
  labels:
    app: weby
  name: weby
  namespace: default
