apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: weby_develop
  name: weby_develop
  namespace: default
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: weby_develop
      port:
        number: 3000
  rules:
  - host: weby.ufg.br
    http:
      paths:
      - backend:
          service:
            name: weby_develop
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
  - host: portais.weby.ufg.br
    http:
      paths:
      - backend:
          service:
            name: weby_develop
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
