apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: weby
  name: weby
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: weby.ufg.br
    http:
      paths:
      - backend:
          service:
            name: weby
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
  - host: portais.weby.ufg.br
    http:
      paths:
      - backend:
          service:
            name: weby
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
