apiVersion: apps/v1
kind: Deployment
metadata:
  name: weby-develop
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: weby-develop
  template:
    metadata:
      labels:
        app: weby-develop
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: weby-develop
            optional: false
        - secretRef:
            name: weby-develop
            optional: false
        image: registry.cercomp.ufg.br/sysadmin/weby/weby_develop:latest
        imagePullPolicy: Always
        name: weby-develop
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: registry-gitlab-cercomp-dev
