apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jZXJjb21wLnVmZy5iciI6eyJ1c2VybmFtZSI6ImdpdGxhYitkZXBsb3ktdG9rZW4tMSIsInBhc3N3b3JkIjoieWdCVGh6Tnd1Tlp1cVRFeTJoUGEifX19
kind: Secret
metadata:
  name: registry-gitlab-cercomp
  namespace: default
type: kubernetes.io/dockerconfigjson
