stages:
  - build
  - precompile
  - publish

variables:  # https://docs.gitlab.com/ee/ci/variables/
  DOCKER_TLS_CERTDIR: ""
  CI_BRANCH_ENV: $CI_COMMIT_BRANCH
  CI_PROJECT_ENV: ${CI_PROJECT_NAME}_${CI_BRANCH_ENV}
  CI_VERSION_ENV: "1.4.1"
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  STORAGE_BUCKET: ${STORAGE_BUCKET}
  STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
  STORAGE_ACCESS_SECRET: ${STORAGE_ACCESS_SECRET}
  STORAGE_HOST: ${STORAGE_HOST}

before_script:
  - touch docker/.env

build:
  stage: build
  image: docker
  services:
    - docker:dind
  environment:
    name: $CI_COMMIT_REF_NAME
  tags:
    - ssh
  only:
    - master
    - develop
  script:
    #- echo "Como se tivesse rodado! :-D"
    - docker-compose --project-directory docker -f docker/docker-compose.yml build

precompile:
  stage: precompile
  image: registry.cercomp.ufg.br/sysadmin/weby/weby_develop:1.4.1
  environment:
    name: $CI_COMMIT_REF_NAME
  tags:
    - docker
  only:
    - master
    - develop
  dependencies:
    - build
  script:
    ## Install bundler, dependency resolver
    #- gem install bundler:1.16.3
    ## Bundle config
    #- bundle config without development:test
    #- bundle config path vendor/bundle
    ## Bundle install
    #- bundle install --without development test --path vendor/bundle --jobs 4 --retry 3
    # Move file to not acess db
    - mv config/initializers/email.rb config/
    # Assets precompile
    - bundle exec rake assets:precompile --trace
    - bundle exec rake assets:clean
    # Init before system up
    - mv config/email.rb config/initializers/
  artifacts:
    paths:
      - public/assets/.sprockets-manifest-*.json

publish:
  stage: publish
  tags:
    - ssh
  only:
    - master
    - develop
  dependencies:
    - build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker tag $CI_PROJECT_ENV:$CI_VERSION_ENV $CI_REGISTRY_IMAGE/$CI_PROJECT_ENV:$CI_VERSION_ENV
    - docker push $CI_REGISTRY_IMAGE/$CI_PROJECT_ENV:$CI_VERSION_ENV
