stages:
  - build
  - publish

variables:  # https://docs.gitlab.com/ee/ci/variables/
  DOCKER_TLS_CERTDIR: ""
  CI_BRANCH_ENV: $CI_COMMIT_BRANCH
  CI_PROJECT_ENV: ${CI_PROJECT_NAME}_${CI_BRANCH_ENV}
  CI_VERSION_ENV: "1.4.1"

before_script:
  - touch docker/.env

build:
  stage: build
  image: docker
  services:
    - docker:dind
  tags:
    - ssh
  script:
    - docker-compose --project-directory docker -f docker/docker-compose.yml build

publish:
  stage: publish
  tags:
    - ssh
  environment: $CI_BRANCH_ENV
  dependencies:
    - build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker tag $CI_PROJECT_ENV:$CI_VERSION_ENV $CI_REGISTRY_IMAGE/$CI_PROJECT_ENV:$CI_VERSION_ENV
    - docker push $CI_REGISTRY_IMAGE/$CI_PROJECT_ENV:$CI_VERSION_ENV
