stages:
  - build
  - deploy

variables:  # CI_BUILD_ID CI_COMMIT_SHORT_SHA CI_COMMIT_BRANCH
  DOCKER_TLS_CERTDIR: ""
  CI_BRANCH_ENV: $CI_COMMIT_BRANCH
  CI_PROJECT_ENV: $CI_PROJECT_NAME-$CI_BRANCH_ENV
  CI_VERSION_ENV: "1.3"

before_script:
  - touch docker/.env

build:
  stage: build
  image: docker
  services:
    - docker:dind
  tags:
    - ssh
  script:
    - docker-compose --project-directory docker -f docker/docker-compose.yml build

deploy:
  stage: deploy
  tags:
    - ssh
  environment: $CI_BRANCH_ENV
  dependencies:
    - build
  script:
    - echo "Enviando a imagem para $DEPLOY_URL"
    - echo $DEPLOY_PASS | docker login -u "$DEPLOY_USER" --password-stdin "$DEPLOY_URL"
    - docker tag weby:latest $DEPLOY_URL/weby/$CI_PROJECT_ENV:$CI_VERSION_ENV
    - docker push $DEPLOY_URL/weby/$CI_PROJECT_ENV:$CI_VERSION_ENV
  when: manual
