version: '3.4'
services:
  weby:
    image: weby
    container_name: weby
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CI_BRANCH_ENV: ${CI_BRANCH_ENV}
        RAILS_ENV: ${RAILS_ENV}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        STORAGE_BUCKET: ${STORAGE_BUCKET}
        STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
        STORAGE_ACCESS_SECRET: ${STORAGE_ACCESS_SECRET}
        STORAGE_HOST: ${STORAGE_HOST}
        GITLAB_URO: ${GITLAB_URO}
        GITLAB_UROP: ${GITLAB_UROP}
    ports:
      - 3000:3000
    env_file:
      - .env

