apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jZXJjb21wLnVmZy5iciI6eyJ1c2VybmFtZSI6ImdpdGxhYitkZXBsb3ktdG9rZW4tMTUiLCJwYXNzd29yZCI6InI2RVFQdmRGNFUza0c5SjdoR2hOIn19fQ==
kind: Secret
metadata:
  name: registry-gitlab-cercomp
  namespace: default
type: kubernetes.io/dockerconfigjson
